Print_dictionary() displays a nested dictionary. This function can generate an extensive amount of screen output, so it should be used sparingly. It has been included primarily as a research tool. 

In [1]:
import os
import numpy as np

def initialize_memory(filename):
    if os.path.exists(filename): 
        memory = np.load(filename,allow_pickle='TRUE').item()
        return memory 
    return {}

def print_dictionary(memory):
    for key,value in memory.items():
        if isinstance(value,dict):
            items = dict(sorted(value.items()))
            actions = list(items.keys())
            q_values = list(items.values())
            best = np.argmax(q_values)
            print("\nState:\n")
            print(key)
            print("\nRecommended action:",actions[best],"\n")              
            print_dictionary(items)
        else:
            formatted_value = "{:+.12f}".format(value)
            print("action:",key,"\tq-value:",formatted_value)
    return

def main(): 
    memory_file = "test_ltm.npy"
    memory = initialize_memory(memory_file)
    print("Memory Contents")
    print_dictionary(memory)
    return

if __name__ == "__main__":
    main()

Memory Contents

State:

[[5 0 0 6 7 2 0 9 8]
 [6 9 4 8 3 1 7 2 5]
 [0 0 0 0 0 9 0 6 1]
 [0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 0 9]
 [0 8 0 3 0 0 5 7 0]
 [0 0 6 0 1 5 0 3 0]
 [0 4 0 0 0 0 0 0 6]
 [1 0 8 0 0 0 0 4 0]]

Recommended action: [3, 2, 9] 

action: [0, 1, 1] 	q-value: +0.660406147684
action: [0, 1, 3] 	q-value: -2.713150601161
action: [0, 2, 1] 	q-value: +0.590719062167
action: [0, 2, 3] 	q-value: -0.000980209089
action: [0, 6, 3] 	q-value: +0.645699864552
action: [0, 6, 4] 	q-value: -1.386988565194
action: [2, 0, 2] 	q-value: -0.874881985202
action: [2, 0, 3] 	q-value: +0.519712216616
action: [2, 0, 7] 	q-value: +0.517264672037
action: [2, 0, 8] 	q-value: -0.524941489647
action: [2, 1, 2] 	q-value: +0.934276943794
action: [2, 1, 3] 	q-value: -1.486478979096
action: [2, 1, 7] 	q-value: -0.618530464935
action: [2, 2, 2] 	q-value: -0.576176503363
action: [2, 2, 3] 	q-value: -0.271343635163
action: [2, 2, 7] 	q-value: +0.004608200231
action: [2, 3, 4] 	q-value: -0.615820073889
acti

action: [2, 3, 5] 	q-value: +1.203006691792
action: [2, 4, 4] 	q-value: -1.198500417933
action: [2, 4, 5] 	q-value: -0.459908913909
action: [2, 6, 3] 	q-value: +2.142538408078
action: [2, 6, 4] 	q-value: -0.328747009402
action: [3, 0, 2] 	q-value: -0.362886031711
action: [3, 0, 3] 	q-value: +1.314726797106
action: [3, 0, 4] 	q-value: -0.844048874637
action: [3, 1, 1] 	q-value: +1.157403995079
action: [3, 1, 2] 	q-value: +0.258716793205
action: [3, 1, 3] 	q-value: +0.848460600217
action: [3, 1, 5] 	q-value: -1.418687205770
action: [3, 1, 6] 	q-value: -0.475879770395
action: [3, 3, 1] 	q-value: -0.429078918792
action: [3, 3, 2] 	q-value: +1.355347770613
action: [3, 3, 4] 	q-value: +1.269964738686
action: [3, 3, 5] 	q-value: +0.018422146482
action: [3, 4, 2] 	q-value: +1.223017955687
action: [3, 4, 4] 	q-value: +1.077834196351
action: [3, 4, 5] 	q-value: -0.434989651359
action: [3, 4, 6] 	q-value: +0.266161301161
action: [3, 4, 8] 	q-value: -1.938157871333
action: [3, 6, 1] 	q-value: +0.9